name: Test pin actions using action commit map

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: step-security/action-semantic-pull-request@v6
        with:
          types: feat,fix,chore
      - uses: step-security/skip-duplicate-actions@v5
        with:
          do_not_skip: '["release"]'
      - uses: step-security/git-restore-mtime-action@v2
        with:
          pattern: '**/*'
        
      - name: Google Auth (CLI)
        uses: google-github-actions/auth/cli@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
